### ISSUE TITLE
Initial release follow up actions

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-websphere-liberty-operator#8]
Address open comments from https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/3

- [X] renovate settings for images versions
- [X] ~remove jq and awk dependencies in script to retrieve sample app url (or document it) https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/3#discussion_r1481803928~ opened enhancement task https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/issues/18
- [X] scale down complete test cluster
- [X] review Liberty naming https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/3#discussion_r1483213017
- [X] https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/3#discussion_r1483156628
- [x] ~add charts into check yaml precommit in common-dev https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/3#pullrequestreview-1868380603 - opened PR for common-dev https://github.com/terraform-ibm-modules/common-dev-assets/pull/888~ Not to be done anymore
- [X] cleanup comments from code
- [X] make extension output url clickable from UI by prefixing it with "https://"
- [X] remove default region
- [X] cleaning up code
- [X] ~analyze the effort and the utility of polling sample app url availability instead of wait~ opened separated task https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/issues/19

**Comment by vbontempi** [comment]
TODO 

- renovate settings for images versions
- remove jq and awk dependencies in script to retrieve sample app url (or document it)
https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/3#discussion_r1481803928
- analyze the effort and the utility of polling sample app url availability instead of wait

**Comment by vbontempi** [comment]
renovate settings for images versions completed

TODO

- remove jq and awk dependencies in script to retrieve sample app url (or document it)
https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/pull/3#discussion_r1481803928
- analyze the effort and the utility of polling sample app url availability instead of wait
